channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.6
  - twine
  - colored=1.4.2
  - dataclasses
  - more-itertools
  - mypy  # dev
  - types-dataclasses  # dev
  - pytest  # dev
  - coverage  # dev
